Project/MyECommerceProject-master/MyECommerceProject-master/MVC_MyProject/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;

namespace MVC_MyProject.Controllers
{
    public class OrderController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Detail()
        {
            return View();
        }
    }
}

Project/MyECommerceProject-master/MyECommerceProject-master/MVC_MyProject/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using MyECommerce.BLL.Abstract;
using MyECommerce.Entity.Entity;

namespace MVC_MyProject.Controllers
{
    public class ProductController : Controller
    {
        private readonly IGenericRepository<Product> _genericRepository;

        public ProductController(IGenericRepository<Product> genericRepository)
        {
            _genericRepository = genericRepository;
        }
        public IActionResult Index()
        {
            return View();
        }
    }
}

Project/MyECommerceProject-master/MyECommerceProject-master/MVC_MyProject/Controllers/SupplierController.cs
using Microsoft.AspNetCore.Mvc;

namespace MVC_MyProject.Controllers
{
    public class SupplierController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Project/MyECommerceProject-master/MyECommerceProject-master/MVC_MyProject/Controllers/UserController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MVC_MyProject.Models.ViewModels;
using MyECommerce.DAL.Context;
using MyECommerce.Entity.Entity;

namespace MVC_MyProject.Controllers
{
    public class UserController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly MyECommerceContext _myECommerceContext;
        private readonly SignInManager<AppUser> _signInManager;

        public UserController(UserManager<AppUser> userManager,MyECommerceContext myECommerceContext,SignInManager<AppUser> signInManager)
        {
            _userManager = userManager;
            _myECommerceContext = myECommerceContext;
            _signInManager = signInManager;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(RegisterVM registerVM)
        {
            if (ModelState.IsValid)
            {
                AppUser user=new AppUser();

                user.UserName = registerVM.Username;
                user.Email = registerVM.Email;

                var result = await _userManager.CreateAsync(user, registerVM.ConfirmPassword);

                if (result.Succeeded) 
                {   
                    return RedirectToAction("Index","Home");
                }
                else
                {
                    return View(registerVM);
                }

            }
            else { return View(registerVM); }
        }

        public IActionResult Login() 
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginVM loginVM)
        {
            if (ModelState.IsValid)
            {
                var login = await _userManager.FindByNameAsync(loginVM.UserName);

                if (login!=null)
                {
                    var result = await _signInManager.PasswordSignInAsync(login, loginVM.Password, false, false);
                    if (result.Succeeded) 
                    {
                        return RedirectToAction("Index","Home");
                    }
                    else
                    {
                        return View(loginVM);
                    }
                    
                }
                else 
                { 
                    return View() ;
                }

            }
            else
            {
                return View(loginVM);
            }
        }


    }
}

Project/MyECommerceProject-master/MyECommerceProject-master/MVC_MyProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC_MyProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVC_MyProject.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Northwind</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex ">
                    <ul class="navbar-nav flex-grow-1 ">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                        </li>   
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="category" asp-action="Index">Category</a>
                        </li> 
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Supplier" asp-action="Index">Supplier</a>
                        </li> 
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Index">Order</a>
                        </li> 
                    </ul>
                    <ul class="navbar-nav ms-auto">
                        

                        <li class="card bg-dark">
                            <a class="btn btn-dark text-white" asp-action="Create" asp-controller="User">Sing up</a>
                        </li>
                        <li class="card ms-1 bg-dark">
                            <a class="btn btn-dark text-white " asp-action="Login" asp-controller="User">Login</a>
                        </li>

                        <li class="nav-item ms-auto">
    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Mycart">
        <i class="fa-solid fa-cart-shopping"></i>
        <span class="badge bg-secondary position-absolute top-0 end-0">0</span>
    </a>
</li>

                        
                    </ul>
                    
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MVC_MyProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>